version: '3.9'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /var/volumes/postgres_data
      o: bind

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superuser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  

